name: 构建 Windows 可执行文件

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发工作流程

jobs:
  build:
    runs-on: windows-latest  # 在 Windows 环境中运行
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    
    - name: 设置 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # 使用 Python 3.9
        cache: 'pip'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQt5 qrcode pillow
    
    - name: 创建图标文件（如果不存在）
      run: |
        if (-not(Test-Path -Path "app_icon.ico")) {
          Invoke-WebRequest -Uri "https://www.python.org/static/favicon.ico" -OutFile "app_icon.ico"
        }
    
    - name: 构建可执行文件
      run: |
        pyinstaller --name="文件共享工具" --windowed --icon=app_icon.ico --add-data="app_icon.ico;." --onefile file_sharing_server.py
    
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: 文件共享工具
        path: dist/文件共享工具.exe
        
    - name: 创建发布
      if: startsWith(github.ref, 'refs/tags/')  # 只在标签推送时创建发布
      uses: softprops/action-gh-release@v2
      with:
        files: dist/文件共享工具.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
